name: Deploy to Production

on:
  push:
    branches: ["production"]
    paths-ignore:
      - "README.md"
      - "docker-compose.yml"
      - "scripts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Echo version"
        run: |
          gcloud info

      - name: "Install beta"
        run: |
          gcloud components install beta --quiet

      - name: "Build DB"
        run: |
          make build-db

      - name: "Build API"
        run: |
          make build-api

      - name: "Deploy DB"
        run: |
          make deploy-db

      - name: "Deploy API"
        run: |
          make deploy-api

      - name: "Delete old images and revisions"
        continue-on-error: true
        run: |
          make delete-old-revisions
